# behat.yml
default:
    extensions:
        Behat\MinkExtension:
            base_url: http://behat.local:8550/
            goutte: ~
            selenium2:
                wd_host: "http://localhost:8643/wd/hub"
    suites:
        default:
            paths:
                - %paths.base%/../test/feature
            contexts:
                - test\context\LsContext
                - test\context\JsContext
