# behat.yml
default:
    autoload:
        '': %paths.base%/../test/features/bootstrap
    suites:
        default:
            paths:
                - %paths.base%/../test/features
            contexts:
                - test\features\bootstrap\LsContext
