_index:
    path:       /
    methods: [GET]
    defaults:   { _controller: "controller.index:doGet"}
_hello:
    path:       /hello/{name}
    methods: [GET]
    defaults:   { _controller: "controller.hello:doGet"}
