# routes.yml
_hello:
    path:        /hello/{name}
    defaults:    { _controller: "controllers.hello:doGet"}

_article:
    path:        /article/{id}
    defaults:    { _controller: "controllers.article:getArticle"}
    requirements:
        id:  \d+


_phpGuzzleOnlyRoute:
    path:       /phpGuzzleOnly/{name}
    defaults:   { _controller: "controllers.links:doGet"}
    methods:    GET
    host:       phpguzzle.local
    schemes:     HTTPS
    options:    {requiresTranslation:false}

_phpGuzzle2OnlyRoute:
    path:       /phpGuzzle2Only/{name}
    defaults:   { _controller: "controllers.links:doGet"}
    methods:    GET
    host:       "{parameters.mainDomain}2.local"
    options:    {requiresTranslation:true}

