_homeRoute:
    path:       /
    defaults:   { _controller: 'controller.home:doGet'}
    methods:    GET

_numberRoute:
    path:       /number/{id}/lang/{lang}
    defaults:   { _controller: 'controller.number:doGetByIdAndLanguage'}
    methods:    GET
