_helloRoute:
    path:       /hello/{name}
    defaults:   { _controller: 'controller.hello:doGet'}
    methods:    GET
_helloByIdRoute:
    path:       /person/{id}
    defaults:   { _controller: 'controller.person:doGet'}
    methods:    GET
